services:
  http-api-gateway:
    build: ./http-api-gateway
    ports:
      - 8888:8888
    volumes:
      - ./http-api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=8888
  users_service:
    build: ./users-service
    volumes:
      - ./users-service/src:/usr/src/app/src
    command: npm run start:dev
  payment_service:
    build: ./payment-service
    volumes:
      - ./payment-service/src:/usr/src/app/src
    command: npm run start:dev
  nats:
    image: nats
    ports:
      - "4222:4222"  
  mysql_db:
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=hiring_db
      - MYSQL_USER=minhduy
      - MYSQL_PASSWORD=123456
      - MYSQL_TCP_PORT=3307